// Generated by CoffeeScript 1.3.1
var circles, dataset, h, padding, rScale, svg, w, xAxis, xScale, yAxis, yScale, _i;

dataset = [];

w = 800;

h = 600;

padding = 30;

for (_i = 0; _i <= 50; _i++) {
  dataset.push([Math.random() * w, Math.random() * h]);
}

svg = d3.select("body").append("svg").attr("width", w).attr("height", h);

circles = svg.selectAll("circle").data(dataset).enter().append("circle").attr("opacity", .0001);

circles.transition().duration(1000).delay(function(d, i) {
  return i * 25;
}).attr("opacity", .8).attr("fill", "green");

xScale = d3.scale.linear().domain([
  0, d3.max(dataset, function(d) {
    return d[0];
  })
]).range([padding, w - padding * 2.5]);

xAxis = d3.svg.axis().scale(xScale).orient("bottom").ticks(5);

yScale = d3.scale.linear().domain([
  0, d3.max(dataset, function(d) {
    return d[1];
  })
]).range([h - padding, padding]);

yAxis = d3.svg.axis().scale(yScale).orient("left").ticks(5);

rScale = d3.scale.linear().domain([
  0, d3.max(dataset, function(d) {
    return d[1];
  })
]).range([5, 30]);

circles.attr("cx", function(d) {
  return xScale(d[0]);
});

circles.attr("cy", function(d) {
  return yScale(d[1]);
});

circles.attr("r", function(d) {
  return rScale(d[1]);
});

svg.append("g").attr("class", "axis").attr("transform", "translate(0, " + (h - padding) + ")").call(xAxis);

svg.append("g").attr("class", "axis").attr("transform", "translate(" + padding + ", 0)").call(yAxis);
